numero1 = float(input("Insira o primeiro número : "))
numero2 = float(input("Insira o segundo número : "))
soma = numero1+numero2
print("A soma dos dois números é:" ,soma)

#Atividade somando valores flutuantes

nota1 = float(input("Insira a primeira nota : "))
nota2 = float(input("Insira a segunda nota : "))
nota3 = float(input("Insira a terceira nota : "))
nota4 = float(input("Insira a quarta nota : "))

#Media das notas

media = (nota1+nota2+nota3+nota4)/4
print("A media das notas é:" ,media)



